services:
  app:
    build: .
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/cert.pem:/etc/nginx/ssl/cert.pem:ro
      - ./nginx/key.pem:/etc/nginx/ssl/key.pem:ro
    depends_on:
      - app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  node_modules: {}
