name: Deploy to VPS

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 'production' 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug environment variables
        run: |
          echo "GITHUB_REF: ${{ github.ref }}"
          echo "Server IP: ${{ secrets.SERVER_IP }}"
          if [ -n "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
            echo "SSH_KEY is set"
          else
            echo "Error: SSH_PRIVATE_KEY is empty"
          fi

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add VPS to known hosts
        run: ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Pull latest code
        run: ssh root@${{ secrets.SERVER_IP }} 'cd /usr/apps/booking_tg_miniapp && git pull origin main'

      - name: Install dependencies
        run: ssh root@${{ secrets.SERVER_IP }} 'cd /usr/apps/booking_tg_miniapp && npm install'

      - name: Start app
        run: ssh root@${{ secrets.SERVER_IP }} 'bash /usr/apps/booking_tg_miniapp/deploy.sh'