name: Setup Environment

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    environment: 'production'
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add VPS to known hosts
        run: ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with: 
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Update API .env file
        run: |
          ssh root@${{ secrets.SERVER_IP }} '
          echo "DATABASE_URL=\"${{ secrets.DATABASE_URL }}\"" > /usr/apps/booking_tg_miniapp/apps/api/.env
          '