name: Setup SSL

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  setup-ssl:
    runs-on: ubuntu-latest
    environment: 'production'
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add VPS to known hosts
        run: ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Create SSL certificate files
        run: |
          ssh root@${{ secrets.SERVER_IP }} '
          echo "${{ secrets.SSL_CERT }}" > /usr/apps/booking_tg_miniapp/nginx/cert.pem &&
          echo "${{ secrets.SSL_PRIVATE_KEY }}" > /usr/apps/booking_tg_miniapp/nginx/key.pem &&
          chmod 600 /usr/apps/booking_tg_miniapp/nginx/cert.pem /usr/apps/booking_tg_miniapp/nginx/key.pem
          '